[package]
name = "rr_channels"
version = "0.1.0"
authors = ["gatowololo"]
edition = "2018"

[dependencies]
crossbeam-channel = "0.3"
lazy_static = "1.3"
log = "0.4"
env_logger = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.6.5"
# backtrace = "0.3"