[package]
name = "rr_channel"
version = "0.1.0"
authors = ["gatowololo"]
edition = "2018"

[dependencies]
crossbeam-channel = "0.3"
lazy_static = "1.3"
log = "0.4"
env_logger = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# ipc-channel = { git = "https://github.com/servo/ipc-channel", rev = "ee3ccbad71be7d99927d391a032fbe7faea76784" }
# ipc-channel = { path = "../../../ipc-channel" }
ipc-channel = { path = "../ipc-channel" }
rand = "0.6.5"
bincode = "1"

[dev-dependencies]
# ipc-channel = { git = "https://github.com/servo/ipc-channel", rev = "ee3ccbad71be7d99927d391a032fbe7faea76784" }
# ipc-channel = { path = "../../../ipc-channel" }
ipc-channel = { path = "../ipc-channel" }
crossbeam-channel = "0.3"